export const LOGS = {
  CREATE_LOG: 'CREATE_LOG',
  GET_LOGS: 'GET_LOGS',
  DELETE_LOG: 'DELETE_LOG',
  EDIT_LOG: 'EDIT_LOG',
};

export const LOG_ENTRIES = {
  CREATE_LOG_ENTRY: 'CREATE_LOG_ENTRY',
  GET_LOG_ENTRIES: 'GET_LOG_ENTRIES',
  DELETE_LOG_ENTRY: 'DELETE_LOG_ENTRY',
  EDIT_LOG_ENTRY: 'EDIT_LOG_ENTRY',
};
